application: cat-imator
version: 2
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: _go_app
